# Generated by Django 6.0.2 on 2026-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='clicks_per_second',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='cost',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
