# Generated by Django 6.0.2 on 2026-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_upgrade_multiplier_upgrade_clicks_per_second_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upgrade',
            old_name='cost',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
